ordis_main_homepage:
    path: /
    defaults: { _controller: OrdisMainBundle:Index:index }
    
ordis_login_check:
    path: /login_check
    
ordis_logout:
    path: /logout
    
ordis_contacts:
    path: /contacts
    defaults: { _controller: OrdisMainBundle:Contacts:index}
    
ordis_jobs:
    path: /jobs
    defaults: { _controller: OrdisMainBundle:Jobs:index}
    
ordis_ng_jobs:
    path: /ng/jobs
    defaults: { _controller: OrdisMainBundle:Jobs:getNgJobs}
