parameters:
#    ordis_main.example.class: Ordis\MainBundle\Example

services:
#    ordis_main.example:
#        class: %ordis_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
