security:
    encoders:
        Renovate\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Renovate\MainBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                login_path: renovate_main_homepage
                check_path: renovate_login_check
                require_previous_session: false
                
            logout:
                path: renovate_logout

    access_control:
        - { path: ^/users*, roles: ROLE_ADMIN }
        - { path: ^/ng/users/check-tariff, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ng/users/clients*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/users/workers*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/users*, roles: ROLE_ADMIN }
        - { path: ^/documents*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/documents*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/partners*, roles: ROLE_ADMIN }
        - { path: ^/ng/partners, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ng/partners*, roles: ROLE_ADMIN }
        - { path: ^/repairs*, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_WORKER] }
        - { path: ^/ng/repairs, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_WORKER] }
        - { path: ^/ng/repairs/count, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_WORKER] }
        - { path: ^/ng/repairs*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/articles/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/articles/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/articles/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/jobs/add, roles: ROLE_ADMIN }
        - { path: ^/ng/jobs/remove*, roles: ROLE_ADMIN }
        - { path: ^/ng/jobs/edit*, roles: ROLE_ADMIN }
        - { path: ^/ng/news/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/news/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/news/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/results/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/results/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/results/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/shares/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/shares/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/shares/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/services*, roles: ROLE_ADMIN }
        - { path: ^/ng/services/calculator, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ng/services*, roles: ROLE_ADMIN }
        - { path: ^/tariffs/panel*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/tariffs/panel/add*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/tariffs/panel/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/tariffs/panel/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/page-descriptions*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/page-descriptions*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/vacancies/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/vacancies/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/vacancies/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/prices/add, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/prices/remove*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/prices/edit*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/tasks*, roles: ROLE_ADMIN }
        - { path: ^/ng/tasks/add*, roles: ROLE_ADMIN }
        - { path: ^/ng/tasks/edit*, roles: ROLE_ADMIN }
        - { path: ^/ng/tasks/remove*, roles: ROLE_ADMIN }
        - { path: ^/ng/tasks/approve*, roles: ROLE_ADMIN }
        - { path: ^/ng/tasks/decline*, roles: ROLE_ADMIN }
        
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
