security:
    encoders:
        Ordis\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Ordis\MainBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                login_path: ordis_main_homepage
                check_path: ordis_login_check
                require_previous_session: false
                
            logout:
                path: ordis_logout

    access_control:
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
