security:
    encoders:
        Renovate\MainBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: Renovate\MainBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                login_path: renovate_main_homepage
                check_path: renovate_login_check
                require_previous_session: false
                
            logout:
                path: renovate_logout

    access_control:
        - { path: ^/users*, roles: ROLE_ADMIN }
        - { path: ^/ng/users*, roles: ROLE_ADMIN }
        - { path: ^/documents*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/ng/documents*, roles: [ROLE_ADMIN, ROLE_EDITOR] }
        - { path: ^/partners*, roles: ROLE_ADMIN }
        - { path: ^/ng/partners*, roles: ROLE_ADMIN }
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
