renovate_main_homepage:
    path: /
    defaults: { _controller: RenovateMainBundle:Index:index }
    
renovate_login_check:
    path: /login_check
    
renovate_logout:
    path: /logout
    
renovate_contacts:
    path: /contacts
    defaults: { _controller: RenovateMainBundle:Contacts:index}
    
renovate_aboutus:
    path: /aboutus
    defaults: { _controller: RenovateMainBundle:AboutUs:index}
    
renovate_ng_contacts_contactus:
    path: /ng/contacts/contact-us
    defaults: { _controller: RenovateMainBundle:Contacts:contactUsNg}
    
renovate_jobs:
    path: /jobs
    defaults: { _controller: RenovateMainBundle:Jobs:index}
    
renovate_jobs_show_job:
    path: /jobs/{job_name_translit}
    defaults: { _controller: RenovateMainBundle:Jobs:showJob}
    
renovate_ng_jobs:
    path: /ng/jobs
    defaults: { _controller: RenovateMainBundle:Jobs:getJobsNg}
    
renovate_ng_jobs_count:
    path: /ng/jobs/count
    defaults: { _controller: RenovateMainBundle:Jobs:getJobsCountNg}
    
renovate_ng_jobs_add:
    path: /ng/jobs/add
    defaults: { _controller: RenovateMainBundle:Jobs:addJobNg}
    
renovate_ng_jobs_remove:
    path: /ng/jobs/remove/{job_id}
    defaults: { _controller: RenovateMainBundle:Jobs:removeJobNg}
    
renovate_ng_jobs_edit:
    path: /ng/jobs/edit/{job_id}
    defaults: { _controller: RenovateMainBundle:Jobs:editJobNg}
    
renovate_users:
    path: /users
    defaults: { _controller: RenovateMainBundle:Users:index}
    
renovate_ng_users:
    path: /ng/users
    defaults: { _controller: RenovateMainBundle:Users:getUsersNg}
    
renovate_ng_users_count:
    path: /ng/users/count
    defaults: { _controller: RenovateMainBundle:Users:getUsersCountNg}
    
renovate_ng_users_add:
    path: /ng/users/add
    defaults: { _controller: RenovateMainBundle:Users:addUserNg}
    
renovate_ng_users_remove:
    path: /ng/users/remove/{user_id}
    defaults: { _controller: RenovateMainBundle:Users:removeUserNg}
    
renovate_ng_users_edit:
    path: /ng/users/edit/{user_id}
    defaults: { _controller: RenovateMainBundle:Users:editUserNg}
    
renovate_ng_roles:
    path: /ng/roles
    defaults: { _controller: RenovateMainBundle:Roles:getRolesNg}
    
renovate_tariffs:
    path: /tariffs
    defaults: { _controller: RenovateMainBundle:Tariffs:index}
    
renovate_documents:
    path: /documents
    defaults: { _controller: RenovateMainBundle:Documents:index}
    
renovate_ng_documents:
    path: /ng/documents
    defaults: { _controller: RenovateMainBundle:Documents:getDocumentsNg}
    
renovate_documents_upload:
    path: /documents/upload
    defaults: { _controller: RenovateMainBundle:Documents:upload}
    
renovate_news:
    path: /news
    defaults: { _controller: RenovateMainBundle:News:index}
    
renovate_news_show_news:
    path: /news/{news_name_translit}
    defaults: { _controller: RenovateMainBundle:News:showNews}
    
renovate_ng_news:
    path: /ng/news
    defaults: { _controller: RenovateMainBundle:News:getNewsNg}
    
renovate_ng_news_count:
    path: /ng/news/count
    defaults: { _controller: RenovateMainBundle:News:getNewsCountNg}
    
renovate_ng_news_add:
    path: /ng/news/add
    defaults: { _controller: RenovateMainBundle:News:addNewsNg}
    
renovate_ng_news_remove:
    path: /ng/news/remove/{news_id}
    defaults: { _controller: RenovateMainBundle:News:removeNewsNg}
    
renovate_ng_news_edit:
    path: /ng/news/edit/{news_id}
    defaults: { _controller: RenovateMainBundle:News:editNewsNg}
    
renovate_results:
    path: /results
    defaults: { _controller: RenovateMainBundle:Results:index}
    
renovate_results_show_result:
    path: /results/{result_name_translit}
    defaults: { _controller: RenovateMainBundle:Results:showResult}
    
renovate_ng_results:
    path: /ng/results
    defaults: { _controller: RenovateMainBundle:Results:getResultsNg}
    
renovate_ng_results_count:
    path: /ng/results/count
    defaults: { _controller: RenovateMainBundle:Results:getResultsCountNg}
    
renovate_ng_results_add:
    path: /ng/results/add
    defaults: { _controller: RenovateMainBundle:Results:addResultNg}
    
renovate_ng_results_remove:
    path: /ng/results/remove/{result_id}
    defaults: { _controller: RenovateMainBundle:Results:removeResultNg}
    
renovate_ng_results_edit:
    path: /ng/results/edit/{result_id}
    defaults: { _controller: RenovateMainBundle:Results:editResultNg}
    
renovate_articles:
    path: /articles
    defaults: { _controller: RenovateMainBundle:Articles:index}
    
renovate_articles_show_article:
    path: /articles/{article_name_translit}
    defaults: { _controller: RenovateMainBundle:Articles:showArticle}
    
renovate_ng_articles:
    path: /ng/articles
    defaults: { _controller: RenovateMainBundle:Articles:getArticlesNg}
    
renovate_ng_articles_count:
    path: /ng/articles/count
    defaults: { _controller: RenovateMainBundle:Articles:getArticlesCountNg}
    
renovate_ng_articles_add:
    path: /ng/articles/add
    defaults: { _controller: RenovateMainBundle:Articles:addArticleNg}
    
renovate_ng_articles_remove:
    path: /ng/articles/remove/{article_id}
    defaults: { _controller: RenovateMainBundle:Articles:removeArticleNg}
    
renovate_ng_articles_edit:
    path: /ng/articles/edit/{article_id}
    defaults: { _controller: RenovateMainBundle:Articles:editArticleNg}
    
renovate_shares:
    path: /shares
    defaults: { _controller: RenovateMainBundle:Shares:index}
    
renovate_shares_show_share:
    path: /shares/{share_name_translit}
    defaults: { _controller: RenovateMainBundle:Shares:showShare}
    
renovate_ng_shares:
    path: /ng/shares
    defaults: { _controller: RenovateMainBundle:Shares:getSharesNg}
    
renovate_ng_shares_count:
    path: /ng/shares/count
    defaults: { _controller: RenovateMainBundle:Shares:getSharesCountNg}
    
renovate_ng_shares_add:
    path: /ng/shares/add
    defaults: { _controller: RenovateMainBundle:Shares:addShareNg}
    
renovate_ng_shares_remove:
    path: /ng/shares/remove/{share_id}
    defaults: { _controller: RenovateMainBundle:Shares:removeShareNg}
    
renovate_ng_shares_edit:
    path: /ng/shares/edit/{share_id}
    defaults: { _controller: RenovateMainBundle:Shares:editShareNg}
    
renovate_partners:
    path: /partners
    defaults: { _controller: RenovateMainBundle:Partners:index}
    
renovate_ng_partners:
    path: /ng/partners
    defaults: { _controller: RenovateMainBundle:Partners:getPartnersNg}
    
renovate_ng_partners_count:
    path: /ng/partners/count
    defaults: { _controller: RenovateMainBundle:Partners:getPartnersCountNg}
    
renovate_ng_partners_add:
    path: /ng/partners/add
    defaults: { _controller: RenovateMainBundle:Partners:addPartnerNg}
    
renovate_ng_partners_remove:
    path: /ng/partners/remove/{partner_id}
    defaults: { _controller: RenovateMainBundle:Partners:removePartnerNg}
    
renovate_ng_partners_edit:
    path: /ng/partners/edit/{partner_id}
    defaults: { _controller: RenovateMainBundle:Partners:editPartnerNg}
